CREATe TABLE EMPLOYE(
emp_id INT,
name VARCHAR(20),
depart VARCHAR(20)
);
DESCRIBE EMPLOYE;
INSERT INTO EMPLOYE VALUES(1,'Dinesh','Fresher');
SELECT * FROM EMPLOYE;
INSERT INTO EMPLOYE VALUES(2,'Sachin','Developer');
INSERT INTO EMPLOYE VALUES(3,'Dhoni','Manager');
INSERT INTO EMPLOYE VALUES(4,'Kholi','Teamlead');
ALTER TABLE EMPLOYE ADD salary INT;
INSERT INTO EMPLOYE(emp_id,salary)VALUES(1,25000);
INSERT INTO EMPLOYE VALUES(1,'Dinesh','Fresher',25000);
UPDATE Employe
SET salary='25000'
WHERE salary='null'
